# Configuration file

path: 'data/coleta.txt' 
overlap: 0.75
window_param: 60

logging:
  version: 1
  formatters: 
    smartwearable:
      format: "Smart Wearable Report - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: smartwearable
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]